version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "sampleTopic:1:1"

  fake-data-producer:
    build: .
    depends_on:
      - kafka
    network_mode: host
    command:
      - "kafka"
      - "--security-protocol"
      - "PLAINTEXT"
      - "--bootstrap-server"
      - "localhost:9092"
      - "--topic"
      - "sampleTopic"
      - "--nr-messages"
      - "5"
      - "--max-waiting-time"
      - "0"
      - "--model"
      - "address"
